import type { Patient } from "./index";

export const dummyPatients: Patient[] = [
  {
    id: "patient-001",
    name: "Sarah Johnson",
    age: 34,
    conditions: ["Hypertension", "Type 2 Diabetes"],
    riskLevel: "high",
    createdAt: new Date("2023-06-15"),
  },
  {
    id: "patient-002",
    name: "Michael Chen",
    age: 52,
    conditions: ["Coronary Artery Disease", "Hyperlipidemia"],
    riskLevel: "high",
    createdAt: new Date("2023-03-22"),
  },
  {
    id: "patient-003",
    name: "Emily Rodriguez",
    age: 28,
    conditions: ["Asthma", "Allergies"],
    riskLevel: "low",
    createdAt: new Date("2023-09-10"),
  },
  {
    id: "patient-004",
    name: "David Wilson",
    age: 67,
    conditions: ["COPD", "Osteoporosis", "Hypertension"],
    riskLevel: "high",
    createdAt: new Date("2022-11-05"),
  },
  {
    id: "patient-005",
    name: "Jessica Lee",
    age: 41,
    conditions: ["Rheumatoid Arthritis", "Thyroid Disorder"],
    riskLevel: "medium",
    createdAt: new Date("2023-07-30"),
  },
  {
    id: "patient-006",
    name: "Robert Martinez",
    age: 55,
    conditions: ["Atrial Fibrillation", "Heart Failure"],
    riskLevel: "high",
    createdAt: new Date("2023-01-18"),
  },
  {
    id: "patient-007",
    name: "Amanda Brown",
    age: 39,
    conditions: ["GERD", "Anxiety Disorder"],
    riskLevel: "low",
    createdAt: new Date("2023-08-12"),
  },
  {
    id: "patient-008",
    name: "James Taylor",
    age: 71,
    conditions: ["Parkinson's Disease", "Dementia"],
    riskLevel: "high",
    createdAt: new Date("2022-05-20"),
  },
  {
    id: "patient-009",
    name: "Nicole White",
    age: 32,
    conditions: ["Migraines", "Depression"],
    riskLevel: "medium",
    createdAt: new Date("2023-10-01"),
  },
  {
    id: "patient-010",
    name: "Thomas Anderson",
    age: 58,
    conditions: ["Type 2 Diabetes", "Peripheral Neuropathy"],
    riskLevel: "medium",
    createdAt: new Date("2023-04-25"),
  },
];
